### ISSUE TITLE
License / Copyright

### ISSUE THREAD

**Issue by konstin** [konstin/stk-wiki-theme#15]
We need to decide for a License and if and where we mention it.

**Comment by MatthewsSam** [comment]
Hum, I don't think the theme should be necessarily public. I would say it's something "exclusive" to stk, why would someone need a stk mediawiki skin ?

**Comment by MatthewsSam** [comment]
IMHO we can simply write:

MediaWiki Theme by konstin and Sam with links to our blogs/website/whatever

I don't see the "need" of using a license for our website. As I said it's "exclusive" to stk
