### ISSUE TITLE
[idea] Special URLs to important content

### ISSUE THREAD

**Issue by konstin** [konstin/stk-wiki-theme#16]
Currently, the link to directly download the latest STK version for linux is `http://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9/supertuxkart-0.9-linux.tar.gz/download`. It could be useful to create special URLs, e.g. `supertuxkart.net/download/linux/latest`, so it is easier to read and one does always get the latest version from the same URL, even if there was a new release or the sourceforge URL changed. Those short-URLs could would be especially usefull in the wiki.

**Comment by MTres19** [comment]
At least for downloads, you can provide links to https://sourceforge.net/projects/supertuxkart/files/latest/download

**Comment by konstin** [comment]
Is there a similar link for Windows and OS X downloads?

**Comment by MTres19** [comment]
I think it should automatically download the correct version for any OS. I just checked with Android—using the same link, it offers to download the source package instead.

**Comment by MTres19** [comment]
And on Windows, it downloads the Windows installer instead.

**Comment by konstin** [comment]
This is great news as it makes providing a download link much easier. I've just added this to the landing page. Thanks!
