### ISSUE TITLE
link active area

### ISSUE THREAD

**Issue by MatthewsSam** [konstin/stk-wiki-theme#19]
It's a minor detail, but in the menu the active area (where you have to click to get there) is only the red one. It would be better if it was the whole green section (and more intuitive)

![screenshot - 30 08 2015 - 02 10 48](https://cloud.githubusercontent.com/assets/6406045/9565111/7e89e35e-4ebc-11e5-9b64-d30ea3a1ec13.png)

**Comment by konstin** [comment]
The  same happens with the download buttons

**Comment by MatthewsSam** [comment]
apparently for the download btn it's corrected
