### ISSUE TITLE
img repository and CSS URL

### ISSUE THREAD

**Issue by MatthewsSam** [konstin/stk-wiki-theme#2]
For some reason the
    background-image: url('../images/header.jpg');
doesn't work on my installation. I have to use:
    background-image: url('../skins/supertuxkart/images/header.jpg');

Any idea why ?

**Comment by MatthewsSam** [comment]
I temporarily corrected the issue by simply making a link in stk-wiki/ pointing to stk-wiki/skins/supertuxkart/images & one for the font.

**Comment by konstin** [comment]
Have you tried changing `'remoteSkinPath' => 'SuperTuxKart',` in `SuperTuxKart.php:38` ?

**Comment by konstin** [comment]
The readme now properly documents all filenames and settings. Reopen the issue if there are still problems.
