### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by MatthewsSam** [konstin/stk-wiki-theme#22]
Hello

We did a whole new theme and a lot of work has already been done. We should IMHO try to update the wiki has soon as possible, otherwise our work will be useless.

I know there are stuff missing and the theme might not be perfect but I suggest to move toward an update because even if not fully completed the new wiki is already better than the previous one.

What's missing for the project ? It would be cool if we could make it happen. We can also once made public do improvements if we found missing stuff.

**Comment by konstin** [comment]
### What is done
- Create a new theme with header, footer, toolbox and some more 
- Create new pages for Main, Discover, Download and FAQ that make use of the new design

### What is still missing
- [x] Finish the new page for Community
- [x] Setup an up-to-date mediawiki instance on an STK-Team-owned Server with the right url rewriting (important for not breaking links!) and add the skin there.
- [x] Import all relevant pages from the old wiki (There's now a file list in docs/page_names_for_export.txt)
- [x] Create at least some of the new pages that are already referenced in the footer and in the Download page
- [x] re-upload the images (This might be a bit tricky and should be done at the server where the new wiki will be deployed)

### Optional
- [x] See what can be done about translation
- [x] Create a second header for developer pages
- [x] Extensive testing
- [ ] other GitHub issues

**Comment by MatthewsSam** [comment]
Can you give me an account to the new wiki (dev.supertuxkart.net) so I can start to do some changes to articles

My objective is to make the new wiki public before releasing stk 0.9.2

Thanks :)

**Comment by MatthewsSam** [comment]
I have started to clean articles and update them for the new wiki.

The main layout of https://dev.supertuxkart.net/wiki/Discover is done now
There is an issue on the community page. The layout is broken when the website is loaded on a smartphone

Custom css used extensively should be included at the end on the main css of the website.

**Comment by MatthewsSam** [comment]
I'm working on templates to make modifications easiers.

I just enable on the server (dev.supertuxkart.net)
 wfLoadExtension( 'ParserFunctions' );
in the file LocalSetting.php

**Comment by konstin** [comment]
ok, but if this should be included in the readme and the LocalSettings.php example.

**Comment by MatthewsSam** [comment]
Ok now, the website is up and running and sourceforge traffic is redirected to supertuxkart.net.

There are a few things missing

1) do a proper redirection (with html and not javascript + taking into account where users wants to go (this is useful for users but also to help google referencing).

2) piwik analytic module

3) testing to be sure everything is working

**Comment by konstin** [comment]
Re 1) This has to be done by someone with admin access to the sourceforge website.

Re 2) piwik is up&running. I can give you the credentials.

RE 3) imho the site is tested well enough

**Comment by MatthewsSam** [comment]
Hum not sure if everything is tested. Sure the main core is working but the donation page should be improved and completely transfered to the new website

**Comment by MatthewsSam** [comment]
Also can you send me the credentials please :)

**Comment by MatthewsSam** [comment]
The donation page is now partially upgraded, the page to download the gift is still not done

**Comment by konstin** [comment]
The wiki is up and running for quite some time without major problems.
