### ISSUE TITLE
set of Icons

### ISSUE THREAD

**Issue by MatthewsSam** [konstin/stk-wiki-theme#23]
You asked me to create a set of icons for the get involved page. After some thoughts and since we already use font awesome why not using their set, to get an unified style.

My selection

Add-on repository icon
https://fortawesome.github.io/Font-Awesome/icon/puzzle-piece/

Github
https://fortawesome.github.io/Font-Awesome/icon/github/

Roadmap
https://fortawesome.github.io/Font-Awesome/icon/map-o/

Media repository
https://fortawesome.github.io/Font-Awesome/icon/picture-o/
or https://fortawesome.github.io/Font-Awesome/icon/file-image-o/

Donate money (imho it should be replaced by support us)
https://fortawesome.github.io/Font-Awesome/icon/heart/

For programmers
https://fortawesome.github.io/Font-Awesome/icon/file-code-o/

For everyone
https://fortawesome.github.io/Font-Awesome/icon/user/

I suggest to add a third category: For artists
https://fortawesome.github.io/Font-Awesome/icon/paint-brush/

I think those icons are sufficient, of course size/color/placement can be tweaked/improved compared to the current version.
If we want custom icons I can always design them, for instance the road map icon could be tweaked/improved.

I think the font awesome layout/design/style is fine for our new website.

**Comment by konstin** [comment]
Using fontawesome is a great idea. I've updated the community page accordingly and also added some other tweaks.

What I still need for the new community page is three icons:
- IRC
- Mailing list
- Sourceforge

btw You can find all the sources for the redesgined pages in the [docs folder](https://github.com/konstin/STK-wiki-theme/tree/master/docs)

**Comment by MTres19** [comment]
I made an icon for IRC. It might not quite fit the theme, but tell me what you think:
![irc](https://cloud.githubusercontent.com/assets/18179456/17600596/2fef1020-5fd2-11e6-9cbd-772b94fd10ba.png)

With a quick Google search, I found [this](https://a.fsdn.com/con/img/features/sf-logo.png) for SourceForge. But I also found [this](https://sourceforge.net/p/forge/documentation/SourceForge%20Logo/). I don't know what logos are available, but I sure hope this is one of them. It says modifying the logo is not allowed.

**Comment by auriamg** [comment]
I'm not sure the little computers at the end of the lines will be very clear/visible when the icon is scaled down. Why not something like the usual http://cdn.juicycocktail.com/images/blog/irc_plugin-icon.png ?

**Comment by MTres19** [comment]
That's true. I've created a version similar to that but more in line with the rest of the icons:
![irc](https://cloud.githubusercontent.com/assets/18179456/17683710/711dd050-6323-11e6-8110-02d43797f017.png)

**Comment by konstin** [comment]
Looks good!

**Comment by MTres19** [comment]
Thanks, I just noticed one of the lines isn't quite straight. I'll fix it and upload the SVG. But how does this get integrated with FontAwesome?

**Comment by MTres19** [comment]
I've pushed two commits so that the remaining icons are usable. However, it needs to be uploaded to the wiki. I was able to test the font but MediaWiki didn't like the `@font-face` property being set on the Community page and disabled any CSS embedded in the page, so it needs to be part of the skin for it to work.

**Comment by MTres19** [comment]
The rest of the Community icons are now up. I think this can be closed.
