### ISSUE TITLE
Big pictures trigger a "bug"

### ISSUE THREAD

**Issue by MatthewsSam** [konstin/stk-wiki-theme#25]
When I wanted to work on the poster page (https://dev.supertuxkart.net/wiki/Posters) I uploaded one of the poster to check

Error creating thumbnail: File with dimensions greater than 12.5 MP

But the file was uploaded and is available
https://dev.supertuxkart.net/images/e/e8/OfficialPoster_091.jpg

**Comment by konstin** [comment]
I've fixed the error by increasing the limit of `$wgMaxImageArea` in `LocalSettings.php`. The new limit is now 10000x10000 pixels.
