### ISSUE TITLE
Coding sections not aligned with bullet points

### ISSUE THREAD

**Issue by hiker** [konstin/stk-wiki-theme#27]
https://dev.supertuxkart.net/wiki/Coding_Style#Layout
The code sections are not aligned with the bullets, and (even worse) the text following the code sections are then not aligned anymore (e.g. see first two code sections and text in between, and compare with the old look: http://supertuxkart.sourceforge.net/Coding_Style#Layout)

@auriamg mentioned on irc:
(11:01:28 AM) Auria: hiker: on the old website, I don't think it actually works on purpose... I think on the old website it just looks indented because the bullets are in the margin
(11:02:50 AM) Auria: samuncle__: easy fix : in the CSS, just use margin-left:0px on ul

**Comment by konstin** [comment]
The main problem is that the new code blocks are outside the list and therefore split one `<ul>` in multiple `<ul>`s. This can be hidden by using `margin-left`, though it's only a workaround.

**Comment by auriamg** [comment]
Actually even on the old wiki the same was also true. The difference was that bullet points used to be in the margin, so text would remain aligned. The easy fix is to remove the left margin on the ul, using margin-left: 0

**Comment by MTres19** [comment]
I know this wasn't part of the problem here, but I fixed the overflowing text on mobile devices by setting overflow to auto. I'll try to work on this and see what I can come up with.

**Comment by MTres19** [comment]
Here's a solution: https://www.mediawiki.org/wiki/Extension:ComplexList

It lets you have multiple paragraphs (and therefore block elements) in one list item. Unfortunately, it's not maintained anymore and it might not be safe, since the code is on the wiki page.

**Comment by MTres19** [comment]
Another solution is to just use `ol`s and `li`s instead of MediaWiki's lists.

**Comment by MTres19** [comment]
Fixed in 959aeccd1b23507f86be25fd77befb1ece98fcfc. Finally!
