### ISSUE TITLE
Language links

### ISSUE THREAD

**Issue by MatthewsSam** [konstin/stk-wiki-theme#3]
In the tool box there is a space for language link.
Should we use this ?
How should we show translation ? I think the main pages in our wiki are translated. (like download etc).
Also will the main page be translated ? (the front page) it would be fine but it seems some extra work

**Comment by konstin** [comment]
I'm definitely for having language links and - if this is possible - also automated client language detection, but I'm not sure where to place the language selection.

**Comment by MatthewsSam** [comment]
What should be translated ? That's another question. There is also the burden of keeping updated translated version

**Comment by MTres19** [comment]
Why not just use [this](https://www.mediawiki.org/wiki/Extension:Google_Translator)? Or provide links to https://translate.google.com/translate?hl=en&tl=af&u=https%3A%2F%2Fsupertuxkart.net%2FMain_Page.

^ That's for Afrikaans.

**Comment by konstin** [comment]
Because google translator's translations are of very low quality in comparison to human translations and is especially bad when it comes to technical content which prevails in the wiki. I can't talk about Afrikaans here, but I looked at the German version and it is horrible.

I'm for simply having no translations.

**Comment by MTres19** [comment]
That's true---I can also attest to the poor German translations, though I only have limited knowledge of German. But for people who have no English knowledge, it would be better than nothing, and (though I don't intend to make a stereotype) those people are unlikely to be in a position to be able to make use of technical documentation anyway.

Another option would be to translate only non-technical pages. @samuncle already writes French translations of some of the blog posts, but perhaps it would be better to avoid trying to translate content that is constantly changing.

**Comment by konstin** [comment]
The non-english speaking users will find sufficient  information on "local" websites writing about STK. So imho there's no point in having outdated translations.
