### ISSUE TITLE
Code blocks linebreaks not respected

### ISSUE THREAD

**Issue by auriamg** [konstin/stk-wiki-theme#30]
This can be seen for instance on https://supertuxkart.net/Building_and_packaging_on_OSX

The wiki source says

```
<code>mkdir cmake_build
cd cmake_build
cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_C_COMPILER=/usr/bin/gcc
make
</code>
```

but it appears as

```
mkdir cmake_build cd cmake_build cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_C_COMPILER=/usr/bin/gcc make
```

**Comment by auriamg** [comment]
I pushed a fix in branch Code_tags, please review, merge and deploy?

https://github.com/konstin/stk-wiki-theme/tree/Code_tags

**Comment by auriamg** [comment]
It's merged, but could you please deploy the fix? The website is still broken

**Comment by konstin** [comment]
Sorry, but I can't deploy until the ssh access is fixed.

**Comment by konstin** [comment]
Fix deployed.
