### ISSUE TITLE
Weird image behavior with JavaScript enabled

### ISSUE THREAD

**Issue by MTres19** [konstin/stk-wiki-theme#32]
I made a [template](https://supertuxkart.net/Template:ArtPortalNav) for navigating pages in the Art Portal. It uses CSS3 flexible boxes for a nice responsive design, and I copied an undo arrow from KDE's Breeze icon set to use for the "Return to Art Portal" link. Unfortunately, when JavaScript is enabled, this arrow disappears after a few times of resizing the window to a small size and then expanding it again. Any ideas, @konstin? Thanks.

**Comment by auriamg** [comment]
The image appears to be assigned height="0", this is caused by the following bit of code:

```
        function handleResizeStart() {
            $galleries.children('li').each(function() {
                var imgWidth = $(this).data('imgWidth'), imgHeight = $(this).data('imgHeight'), width = $(this).data('width'), captionWidth = $(this).data('captionWidth'), $innerDiv = $(this).children('div').first(), $imageDiv = $innerDiv.children('div.thumb'), $imageElm, imageElm;
                $(this).width(width);
                $innerDiv.width(width);
                $imageDiv.width(imgWidth);
                $(this).find('div.gallerytextwrapper').width(captionWidth);
                $imageElm = $(this).find('img').first();
                imageElm = $imageElm.length ? $imageElm[0] : null ;
                if (imageElm) {
                    imageElm.width = imgWidth;
                    imageElm.height = imgHeight;
                } else {
                    $imageDiv.height(imgHeight);
                }
            });
        }
```

I am not sure where this code comes from or what it is intended to do, however

**Comment by MTres19** [comment]
Looks like it's part of the MediaWiki galleries thing. After some trial and error, I kinda hacked things together with a "nolines" gallery mode instead of "packed" mode and a span to increase the margins. So I guess it's a MediaWiki deficiency.
