### ISSUE TITLE
Cannot login on mediawiki

### ISSUE THREAD

**Issue by auriamg** [konstin/stk-wiki-theme#33]
It says

```
There seems to be a problem with your login session; this action has been canceled as a precaution against session hijacking. Go back to the previous page, reload that page and then try again.
```

reproduced by several people

**Comment by auriamg** [comment]
May be related to https://www.mediawiki.org/wiki/Topic:T7irqyk4rhfy3ohk

**Comment by auriamg** [comment]
As described in the link above, I've done this :

```
 change $wgMainCacheType from CACHE_ACCEL to CACHE_ANYTHING
```

It appears to work. However, I'm not sure if the cache setting that was there was a deliberate choice?

**Comment by MTres19** [comment]
It works for me.

**Comment by konstin** [comment]
> It appears to work. However, I'm not sure if the cache setting that was there was a deliberate choice?

Yes, because I installed php-apc as cache. Apparently there's a bug in mediawiki 1.27 that makes the login fail with `$wgMainCacheType=CACHE_ACCEL`. Thanks for fixing that.
