### ISSUE TITLE
Switch to flexboxes for Community page

### ISSUE THREAD

**Issue by MTres19** [konstin/stk-wiki-theme#34]
I've noticed that the links to GitHub, Sourceforge, the forums, etc. get squashed together on my phone, and the "For programmers" and "For artists" sections end up looking weird. This would be extremely simple to fix with flexboxes and would prevent a lot of a annoyance. I already used flexboxes for my [ArtPortalNav](https://supertuxkart.net/Template:ArtPortalNav) template.  The only problem is that there won't be support for IE < 11, Chrome < 29, Firefox < 28, Safari < 9, and Opera < 17. But most of those versions are absolutely ancient anyway and anyone who bought a computer that didn't come with Win7 (and therefore did not get IE 11) wouldn't be likely to have a good GPU for STK anyway.

**Comment by MTres19** [comment]
The only exception is Safari 9, which was released just under a year ago. But Apple is pretty good at forcing people to update, so I'm not sure if it's a big concern.

**Comment by MTres19** [comment]
Would anyone mind if I fixed this?

**Comment by konstin** [comment]
I just looked up browser usage statistics using piwik and it seems that flexboxes are supported by the great majority of all user browsers, so go ahead and change this :) . According to http://caniuse.com/#feat=flexbox Safari 9 isn't a problem either.

btw our irc channel is a good place to discuss such matters as this one. The STK team might not always be around, but it's always worth quickly asking there.

**Comment by MTres19** [comment]
Okay.

Okay. The main problem I see with IRC is there's no log of what people were talking about before. If you join in the middle of a conversation, it could be pretty confusing, or if you didn't have time to respond at the time but wanted to later. I suppose it's OK for things like this, though.

**Comment by MTres19** [comment]
Okay, both the links and the artist and programmer sections are changed over to flexboxes. The only noticeable change is that the artist and programmer sections are now pushed to the sides of the page, which in my opinion looks better anyway.
