### ISSUE TITLE
Cleanup wiki

### ISSUE THREAD

**Issue by MTres19** [konstin/stk-wiki-theme#36]
There are still a lot of outdated pages even after the transition to the new website, and a lot of pages would be better suited for the Talk namespace. I propose the articles be rearranged a bit, but I can't do this, since I only have a user-level account.

**Pages to delete**
- [x] Screenshots Old (Gallery already has everything nicely arranged with packed &#60;gallery>s.)
- [x] Archived News (The blog archive works perfectly fine.)
- [x] Art portal (**NOT** Art Portal—the capitalization matters.)
- [ ] Dependencies (INSTALL.md is much more likely to be up-to-date.)
- [x] Grand Prix (The XML files explain themselves)
- [x] SuperTuxKart Image Properties (obsoleted by Materials, Physics, and other pages and contains inaccurate/outdated information)
- [x] Object library (Not very useful and will be obsoleted by the Making Library Nodes tutorial)
- [x] Object list (Out-of-date and obsoleted by Needed Objects page)
- [x] Scripting API (Obsoleted by Doxygen)
- [x] Lightmaps (No longer used)
- [x] Licences (This appears to be the French translation of the Licenses page.)
- [x] Let's make a track together (This project was never finished and is obsoleted by the shiny new Making Tracks tutorial anyway, which is just about complete now.)
- [x] Making Tracks:Ideas and Concept Art (Note the lack of a space—this was a mistake on my part when I was making the page and the best I could do was move the page. Right now it just wastes space on the AllPages page.)
- [x] New Blender Tutorial (Double-obsoleted; first by Blender track modelling tutorial and now by Making Tracks: Properties and Modeling.)
- [x] Installing the Tools
- [x] Texture
- [x] Material

**Pages to move to Talk**
- [x] All the GSoC-related pages (or should these be deleted? They certainly don't apply anymore.)
- [x] Greenlight
- [x] Lobby implementation
- [x] Stkaddons client authentication
- [x] Stkaddons:Upload Music
- [x] Milestones
- [x] ToDo
- [x] New particle engine
- [x] New graphical pipeline
- [x] Theoretical Driveline Model
- [x] Networked Multiplayer
- [x] Network implementation
- [x] Tracks (This pages is more of a discussion of track ideas than anything else.)
## 

I also propose that art-related pages obsoleted by the new Art Portal pages should be placed in a new namespace, "Legacy". The reason I see for this is that there is the possibility that some content didn't get ported.

**Pages to move to Legacy:**
- [x] Blender track modelling tutorial
- [x] Universe
- [x] Track Maker's Guide
- [x] Style Guidelines
- [x] Separate or Animated Objects
- [x] New drivelines

**Other miscellaneous items:**
- [x] JoergHenrichs should eventually be moved to User:Hiker when hiker gets a wiki account
- [ ] Kart shadow tutorial may need to be deleted since I think it's no longer used, at least with dynamic shadows enabled.
- [x] The tutorials about the new arena should perhaps be ported from the old site. They're not particularly useful, but do have some information about concept art and such.

**Comment by konstin** [comment]
Your proposed changes look good! I'll have to wait till I get feedback from auria and hiker, then I can give you a real response.

**Comment by auriamg** [comment]
A few notes :

pages superseeded by the new art portal can be archived for sure - once the new art portal is fully complete

"Dependencies (INSTALL.md is much more likely to be up-to-date.)", unsure about that assertion, we do keep the website updated, I'd keep this one

the totally obsolete ones like Lightmap can go for sure

As for archived news and old screenshots, I think we can keep them for the moment

**Comment by MTres19** [comment]
I've pretty much finished the new track making guide. The kart guide doesn't need a huge amount of updating from what I can tell. Just a few corrections and updates to fit in with generic pages like Materials.

The problem is that people who find the GitHub page first might not check the wiki. It's not really a problem if it's kept up to date but it is duplicated work. (I believe @konstin has a PR about this.)

I don't know about Archived News, but Gallery has all the old screenshots too, but uses modern and mobile-friendly MediaWiki syntax.

**Comment by konstin** [comment]
> "Dependencies (INSTALL.md is much more likely to be up-to-date.)", unsure about that assertion, we do keep the website updated, I'd keep this one

That depends on https://github.com/supertuxkart/stk-code/pull/2611

> As for archived news and old screenshots, I think we can keep them for the moment

I'm tend to be for removing, but it's no problem if we keep them for now.

**Comment by konstin** [comment]
@mtres19 As you have already many high quality contributions, I've granted you admin access to the wiki :confetti_ball:. You can now do all the changes you proposed :smiley:

**Comment by MTres19** [comment]
Thank you. I'll get right to it.

**Comment by MTres19** [comment]
@konstin I can't add a namespace because I don't have access to LocalSettings.php. Would you be able to add the "Legacy" namespace? Thanks.

**Comment by vampy** [comment]
@MTres19 I added the `Legacy` namespace.

**Comment by MTres19** [comment]
Seems good enough. Closing.
