### ISSUE TITLE
Header menu active zone

### ISSUE THREAD

**Issue by MatthewsSam** [konstin/stk-wiki-theme#4]
Actually only the text is active (aka you can click to access).

I think it would be better if the whole little column is active so you don't have to put the mouse precisely on the right place.

The current active zone is the green zone and I think we should extend it to the red zone so it's bigger and makes more sense.
![screenshot - 24 05 2015 - 11 50 40](https://cloud.githubusercontent.com/assets/6406045/7787433/12d5100e-020c-11e5-88cf-a7e404d7d2af.jpg)

**Comment by konstin** [comment]
fixed in 41899a9
