### ISSUE TITLE
Change buttons on Download page

### ISSUE THREAD

**Issue by qwertychouskie** [konstin/stk-wiki-theme#40]
First, the hover color should be different:
```
.mw-ui-button:hover {
    background-color: #a1d4a5;
}
```
Second, the buttons should be a bit more logical, e.g.:
![](http://i.imgur.com/WbNqXEU.png)

HTML (needs to be fixed to function with JS:
```
<div class="mw-ui-button os_presentation_title" style="">
  <span class="mw-collapsible-toggle mw-collapsible-toggle-collapsed">
    <a href="#">- <i class="fa fa-linux fa-fw os-icon"></i>Linux</a>
    <div style="display: inline-block;float: right;" class="os_link_container_button">
      <a href="https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/0.9.2/supertuxkart-0.9.2-linux.tar.xz/download" style="display: inline-block;float: right;" rel="nofollow" class="external text os_link_a">
        <p style="margin: 5px 0;font-size: 22px;" class="os_link_description">
          <b>Full game</b> (.tar.xz) <i class="fa fa-download fa-fw"></i>
        </p>
      </a>
    </div>
  </span>
</div>
```

**Comment by konstin** [comment]
> First, the hover color should be different:

No, the current color pallet is fine the way it is.

> Second, the buttons should be a bit more logical, e.g.:

No, the buttons are ok the way they are

> HTML (needs to be fixed to function with JS:

The html is produced by mediawiki and therefore better than some handwritten block that will break with the next mediawiki update.
