### ISSUE TITLE
supertuxkart.net vps disk full....

### ISSUE THREAD

**Issue by Benau** [konstin/stk-wiki-theme#42]
Hi
There is no more space in supertuxkart.net vps anymore, from du it says the backup files of piwik eat most of the space.

Quick fix will be remove some old backups, but actually is piwik stats actually being analysed by anyone else atm? Otherwise maybe we should just remove piwik in stk vps...

**Comment by konstin** [comment]
I don't use that piwik anymore and don't know of anyone who is using it, so I'm fine with removing it.

**Comment by Benau** [comment]
now it's freed 6GB! ![](https://lihkg.com/assets/faces/pig/free.gif)![](https://lihkg.com/assets/faces/pig/free.gif)![](https://lihkg.com/assets/faces/pig/free.gif)
